name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Web app Docker image
      run: |
        docker build -t your-dockerhub-username/web-app:latest -f web/Dockerfile .
        docker push your-dockerhub-username/web-app:latest

    - name: Build and push API Docker image
      run: |
        docker build -t your-dockerhub-username/api:latest -f api/Dockerfile .
        docker push your-dockerhub-username/api:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
